#!/usr/bin/env python3
"""
Friday Image Pipeline — LoRA Training Dataset Exporter

Packages approved pipeline images into a kohya_ss-compatible training dataset.
Output structure:

  <output_dir>/
    img/
      <repeat>_<trigger>/          # e.g. "10_friday"
        *.png                      # approved images
        *.txt                      # per-image caption files
    log/
    model/
    dataset_config.toml            # kohya_ss dataset config
    training_config.toml           # kohya_ss training hyperparams (SDXL LoRA defaults)
    README.md                      # instructions for starting the training run

Usage:
  python lora_export.py
  python lora_export.py --trigger friday --repeats 15 --out ~/lora-dataset
  python lora_export.py --approved-only          # default, but explicit
  python lora_export.py --all                    # include unapproved too

Cards: bridges Image LLM Pipeline (card #10) → Friday Likeness LoRA (card #38)
"""

import argparse
import json
import os
import shutil
from datetime import datetime
from pathlib import Path

# Re-use pipeline's state loading
import sys
sys.path.insert(0, str(Path(__file__).parent))
from pipeline import OUTPUT_DIR, STATE_FILE, load_state, get_base_prompt

# ── Defaults ──────────────────────────────────────────────────────────────────
DEFAULT_TRIGGER = "friday"
DEFAULT_REPEATS = 10         # kohya_ss repeats multiplier (higher = more training weight)
DEFAULT_OUT = OUTPUT_DIR / "lora_dataset"

KOHYA_TRAIN_TOML_TEMPLATE = """\
# kohya_ss SDXL LoRA training config — generated by Friday Image Pipeline
# Run from the kohya_ss directory:
#   python train_network.py --config_file {config_path}

[model_arguments]
pretrained_model_name_or_path = "stabilityai/stable-diffusion-xl-base-1.0"
# Or replace with your local SDXL checkpoint path, e.g.:
# pretrained_model_name_or_path = "/path/to/juggernaut-xl-v9.safetensors"

[saving_arguments]
save_model_as = "safetensors"
output_name = "friday_likeness_v1"
output_dir = "./model"
save_every_n_epochs = 1

[network_arguments]
# LoRA config
network_module = "networks.lora"
network_dim = 32
network_alpha = 16
network_args = ["preset=full"]

[training_arguments]
max_train_steps = 0            # use epochs instead
num_train_epochs = 10
train_batch_size = 1
gradient_accumulation_steps = 1
learning_rate = 1e-4
unet_lr = 1e-4
text_encoder_lr = 5e-5
lr_scheduler = "cosine"
lr_warmup_steps = 0
mixed_precision = "fp16"
save_precision = "fp16"
optimizer_type = "AdamW8bit"
xformers = true
gradient_checkpointing = true
cache_latents = true
max_token_length = 225
seed = 42

[dataset_arguments]
# Dataset config is in dataset_config.toml; pass it via --dataset_config
# dataset_config = "{dataset_config_path}"

[logging_arguments]
log_with = "tensorboard"
logging_dir = "./log"
"""

KOHYA_DATASET_TOML_TEMPLATE = """\
# kohya_ss dataset config — generated by Friday Image Pipeline
# Pass to train_network.py via --dataset_config

[general]
shuffle_caption = true
caption_extension = ".txt"
keep_tokens = 1           # keep trigger token first when shuffling

[[datasets]]
resolution = 1024
batch_size = 1
enable_bucket = true
min_bucket_reso = 768
max_bucket_reso = 1024
bucket_reso_steps = 64

  [[datasets.subsets]]
  image_dir = "{img_dir}"
  class_tokens = "{trigger}"
  num_repeats = {repeats}
"""

README_TEMPLATE = """\
# Friday Likeness LoRA — Training Dataset

Generated by the Friday Image Pipeline on {date}.

## Contents

- `img/{repeats}_{trigger}/` — {n_images} training images with captions
- `dataset_config.toml` — kohya_ss dataset configuration
- `training_config.toml` — kohya_ss training hyperparameters (SDXL LoRA defaults)

## Hardware requirements (Friday's host)
- RTX 4070 SUPER (12GB VRAM) — tight but feasible for SDXL LoRA with gradient checkpointing
- ~6–8 hours for 10 epochs on {n_images} images

## Quick start (kohya_ss)

```bash
# 1. Clone kohya_ss if you haven't
git clone https://github.com/bmaltais/kohya_ss.git
cd kohya_ss

# 2. Install deps
pip install -r requirements.txt

# 3. Launch training
python train_network.py \\
  --config_file {config_path} \\
  --dataset_config {dataset_config_path}
```

## Trigger token
Use `{trigger}` in your prompts after training to activate the LoRA identity.

Example: `{trigger}, at her desk coding, cyberpunk lighting`

## Recommended settings for inference
- LoRA weight: 0.7–0.9
- Steps: 25–30
- CFG: 6–8
- Sampler: DPM++ 2M Karras

## Next steps
1. Collect more reference images (aim for 20–30 for best results)
2. Re-export dataset and retrain when new approved images are added
3. Wire the trained `.safetensors` into the pipeline via `--lora` flag (TODO)
"""


def caption_for_run(run: dict, trigger: str) -> str:
    """Generate a per-image caption for kohya_ss training.

    Format: <trigger>, <scene description, cleaned up>
    The trigger must come first — kohya_ss keep_tokens=1 pins it.
    """
    scene = run.get("scene", "").strip()
    if not scene:
        return trigger

    # Strip "Friday" variants from scene since trigger covers it
    import re
    scene_clean = re.sub(r"\bfriday\b", "", scene, flags=re.IGNORECASE).strip(" ,—-")
    scene_clean = re.sub(r"\s+", " ", scene_clean).strip(" ,")
    scene_clean = re.sub(r"^[,\s]+", "", scene_clean)

    # Compose caption
    return f"{trigger}, {scene_clean}" if scene_clean else trigger


def export_lora_dataset(
    out_dir: Path,
    trigger: str = DEFAULT_TRIGGER,
    repeats: int = DEFAULT_REPEATS,
    approved_only: bool = True,
) -> dict:
    """Export approved pipeline images as a kohya_ss training dataset.

    Returns a summary dict.
    """
    state = load_state()
    runs = state.get("runs", {})

    # Filter runs
    if approved_only:
        target_runs = [r for r in runs.values() if r.get("approved") and r.get("images")]
    else:
        target_runs = [r for r in runs.values() if r.get("status") == "done" and r.get("images")]

    if not target_runs:
        return {"ok": False, "reason": "No eligible runs found (no approved images with status=done)."}

    # Build directory structure
    img_subdir = out_dir / "img" / f"{repeats}_{trigger}"
    img_subdir.mkdir(parents=True, exist_ok=True)
    (out_dir / "log").mkdir(exist_ok=True)
    (out_dir / "model").mkdir(exist_ok=True)

    images_exported = 0
    run_ids_exported = []

    for run in target_runs:
        for img_path_str in run.get("images", []):
            img_src = Path(img_path_str)
            if not img_src.exists():
                print(f"  ⚠️  Image not found: {img_src} — skipping")
                continue

            run_id = run.get("id", run.get("run_id", "unknown"))[:8]
            version = run.get("version", 1)
            dest_name = f"{run_id}_v{version}_{img_src.name}"
            dest = img_subdir / dest_name
            shutil.copy2(img_src, dest)

            # Write caption file (same name, .txt)
            caption = caption_for_run(run, trigger)
            caption_file = img_subdir / (dest.stem + ".txt")
            caption_file.write_text(caption, encoding="utf-8")

            print(f"  ✅ {dest.name}")
            print(f"     Caption: {caption[:80]}")
            images_exported += 1
            if run_id not in run_ids_exported:
                run_ids_exported.append(run_id)

    if images_exported == 0:
        return {"ok": False, "reason": "Ran but no images were found on disk."}

    # Write kohya_ss config files
    dataset_config_path = out_dir / "dataset_config.toml"
    training_config_path = out_dir / "training_config.toml"

    dataset_toml = KOHYA_DATASET_TOML_TEMPLATE.format(
        img_dir=str(img_subdir),
        trigger=trigger,
        repeats=repeats,
    )
    dataset_config_path.write_text(dataset_toml, encoding="utf-8")

    train_toml = KOHYA_TRAIN_TOML_TEMPLATE.format(
        config_path=str(training_config_path),
        dataset_config_path=str(dataset_config_path),
    )
    training_config_path.write_text(train_toml, encoding="utf-8")

    # Write README
    readme = README_TEMPLATE.format(
        date=datetime.utcnow().strftime("%Y-%m-%d"),
        trigger=trigger,
        repeats=repeats,
        n_images=images_exported,
        config_path=str(training_config_path),
        dataset_config_path=str(dataset_config_path),
    )
    (out_dir / "README.md").write_text(readme, encoding="utf-8")

    # Write a manifest JSON
    manifest = {
        "exported_at": datetime.utcnow().isoformat(),
        "trigger": trigger,
        "repeats": repeats,
        "approved_only": approved_only,
        "n_images": images_exported,
        "run_ids": run_ids_exported,
        "img_dir": str(img_subdir),
        "dataset_config": str(dataset_config_path),
        "training_config": str(training_config_path),
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    return {
        "ok": True,
        "n_images": images_exported,
        "run_ids": run_ids_exported,
        "out_dir": str(out_dir),
        "img_dir": str(img_subdir),
        "dataset_config": str(dataset_config_path),
        "training_config": str(training_config_path),
    }


def main():
    parser = argparse.ArgumentParser(
        description="Export approved pipeline images as a LoRA training dataset (kohya_ss format)"
    )
    parser.add_argument(
        "--trigger", default=DEFAULT_TRIGGER,
        help=f"Trigger token / class name (default: {DEFAULT_TRIGGER})"
    )
    parser.add_argument(
        "--repeats", type=int, default=DEFAULT_REPEATS,
        help=f"kohya_ss num_repeats (default: {DEFAULT_REPEATS})"
    )
    parser.add_argument(
        "--out", default=str(DEFAULT_OUT),
        help=f"Output directory (default: {DEFAULT_OUT})"
    )
    parser.add_argument(
        "--all", dest="include_all", action="store_true",
        help="Include all done runs, not just approved ones"
    )
    args = parser.parse_args()

    out_dir = Path(args.out).expanduser().resolve()
    approved_only = not args.include_all

    print(f"\n🗂  Friday LoRA Dataset Export")
    print(f"   Trigger  : {args.trigger}")
    print(f"   Repeats  : {args.repeats}")
    print(f"   Filter   : {'approved only' if approved_only else 'all done runs'}")
    print(f"   Output   : {out_dir}\n")

    result = export_lora_dataset(out_dir, args.trigger, args.repeats, approved_only)

    if not result["ok"]:
        print(f"\n❌ Export failed: {result.get('reason')}")
        sys.exit(1)

    print(f"\n✅ Dataset ready — {result['n_images']} images exported")
    print(f"   Runs: {', '.join(result['run_ids'])}")
    print(f"\n📁 {result['out_dir']}/")
    print(f"   img/{args.repeats}_{args.trigger}/   ← training images + captions")
    print(f"   dataset_config.toml          ← pass to --dataset_config")
    print(f"   training_config.toml         ← kohya_ss SDXL LoRA hyperparams")
    print(f"   README.md                    ← full training instructions")
    print(f"\nNext: run kohya_ss train_network.py with the configs above.")
    print(f"See {result['out_dir']}/README.md for the full walkthrough.")


if __name__ == "__main__":
    main()
